# Generated by Django 4.2.6 on 2023-11-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='importand',
            new_name='important',
        ),
    ]
